const events = [{
    id: '0',
    name: 'Cinema event',
    description: 'Watch this film in the cinema',
    image: 'assets/cinema.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 879,
    tag: 'Entertainment',
}, {
    id: '1',
    name: 'Example',
    description: 'This is an example description',
    image: 'assets/concert.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 4500,
    tag: 'Entertainment',
}, {
    id: '2',
    name: 'Drinks',
    description: 'Join us for drinks',
    image: 'assets/drinks.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 0,
    tag: 'Food & Drink',
}, {
    id: '3',
    name: 'BBQ',
    description: 'This is a BBQ party',
    image: 'assets/hotdogs.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 200,
    tag: 'Food & Drink',
}, {
    id: '4',
    name: 'The office',
    description: 'An office event',
    image: 'assets/office.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 0,
    tag: 'Work',
}, {
    id: '5',
    name: 'Pizza night',
    description: 'Come over for pizza night',
    image: 'assets/pizza.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 450,
    tag: 'Food & Drink',
}, {
    id: '6',
    name: 'Coding',
    description: 'Coding task',
    image: 'assets/skeleton.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 0,
    tag: 'Work',
}, {
    id: '7',
    name: 'A Play',
    description: 'Watch this play in the theatre',
    image: 'assets/theatre.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 7599,
    tag: 'Entertainment',
}, {
    id: '3',
    name: 'BBQ',
    description: 'This is a BBQ party',
    image: 'assets/hotdogs.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 200,
    tag: 'Food & Drink',
}, {
    id: '4',
    name: 'The office',
    description: 'An office event',
    image: 'assets/office.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 0,
    tag: 'Work',
}, {
    id: '5',
    name: 'Pizza night',
    description: 'Come over for pizza night',
    image: 'assets/pizza.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 450,
    tag: 'Food & Drink',
}, {
    id: '6',
    name: 'Coding',
    description: 'Coding task',
    image: 'assets/skeleton.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 0,
    tag: 'Work',
}, {
    id: '7',
    name: 'A Play',
    description: 'Watch this play in the theatre',
    image: 'assets/theatre.jpg',
    date: new Date(Math.round(Math.random() * 1665696556222)),
    price: 7599,
    tag: 'Entertainment',
},]